version: '3'
services:
  entry_proxy: # 项目的service name
    container_name: 'entry' #容器名称
    image: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./entry/:/etc/nginx/
    extra_hosts:
      - "host.docker.internal:host-gateway"
  docs:
    build: {
       context: ../, # 设置根目录作为dockerfile执行的上下文
       dockerfile: ops/docs/Dockerfile
    }
    restart: always
    ports:
      - 3000:80
    volumes:
      - ./docs/nginx.conf:/etc/nginx/nginx.conf #挂载nginx配置
    extra_hosts:
      - "host.docker.internal:host-gateway"
