on:
  push:
  pull_request_target:
    branches: [main]
name: syncToGitee
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Mirror Github to Gitee with white list and cache
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/${{ github.repository }}
          dst: gitee/${{ secrets.GITEE_USERNAME }}/${{ github.event.repository.name }}
          dst_key: ${{ secrets.GITEE_TOKEN }}
          force_update: true
          static_list: "xrepo"
